# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vldzm1015
brief-intro: min's study note
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vldzm1015.github.io" # the base hostname & protocol for your site
timezone: Asia/Seoul

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username:  vldzm1015
email: vldzm1015@gmail.com
#weibo_username:
#zhihu_username:
#linkedIn_username:
#dribbble_username:

description_footer: bye

# comments
# two ways to comment, only choose one, and use your own short name
#duoshuo_shortname: #hygblog
disqus_shortname: vldzm1015

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
#baidu_tongji_id:
google_analytics_id: UA-140432992-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
